Formulario/Models/ErrorViewModel.cs
using System;

namespace Formulario.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Formulario/Models/Formulario.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Formulario.Models
{
       [Table("t_bono")]
     
    public class Formularios
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("id")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Por favor ingrese un Nombre")]
        [Display(Name="name")]
        [Column("name")]

        public string nombre { get; set; }

        [Required(ErrorMessage = "Por favor ingrese un Apellido")]
        [Display(Name="lastname")]
        [Column("lastname")]

        public string apellido { get; set; }

        [Required(ErrorMessage = "Por favor ingrese un Distrito")]
        [Display(Name="district")]
        [Column("district")]

        public string distrito { get; set; }


        [Column("bank")]

        public string banco { get; set; }


        [Column("age")]

        public int edad { get; set; }


        [Column("gender")]

        public string genero { get; set; }

        [Column("author")]

        public string author { get; }

        [NotMapped]

        public String Respuesta { get; set; }
    }
}

Formulario/Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Formulario.Models;
using Formulario.Data;
namespace Formulario.Controllers
{
    public class FormularioController : Controller
    {
        private readonly ILogger<FormularioController> _logger;

        public FormularioController(ILogger<FormularioController> logger,DatabaseContext context)
        {
            _logger = logger;
             _context = context;

        }

        public IActionResult Index()
        {
            return View();
        }
  private readonly DatabaseContext _context;
 [HttpPost]
           public IActionResult Enviar(Formularios objFormulario){

               if(ModelState.IsValid){
                objFormulario.Respuesta = "Gracias, hemos procesado su solicitud";
                _context.Add(objFormulario);
                _context.SaveChanges();
               }
               
                 return View("index", objFormulario);
        }
    }
    
}

Formulario/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Formulario.Models;

namespace Formulario.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Formulario/Views/Formulario/Index.cshtml
@model Formulario.Models.Formularios

@{
    ViewData["Title"] = "Hecho por Omar Poma";
}

<div class="row">
    <div class="col-md-4">  
        <h1 class="display-4">Solicitud de Bono</h1>
        <hr color="black" size=3>
        <form asp-controller="Formulario" asp-action="Enviar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label">Nombre</label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>    

            <div class="form-group">
                <label asp-for="apellido" class="control-label">Apellido</label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="distrito" class="control-label">Distrito</label>
                <input asp-for="distrito" class="form-control" />
                <span asp-validation-for="distrito" class="text-danger"></span>
            </div>                 
                   
            <div class="form-group">
                BANCOS AUTORIZADOS:
                <select asp-for="banco" class="form-control">
                    <option value="BANBIF">BANBIF</option>
                    <option value="INTERBANK">INTERBANK</option>
                    <option value="BCP">BCP</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="edad" class="control-label">Edad</label>
                <input asp-for="edad" class="form-control" />
            </div>  

            <div class="form-group">
                Genero:
                <label><input asp-for="genero" type="radio" name="genero" value="F"> Femenino</label>
                <label><input asp-for="genero" type="radio" name="genero" value="M"> Masculino</label>
            </div>                             

            <div class="form-group">
                 <button type="submit" class="btn btn-primary" value="Enviar">Enviar</button> 
            </div>                

        </form>
            
        <td>@Html.DisplayTextFor(model => model.Respuesta)</td>    
    
    </div>
</div>

Formulario/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Formulario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formulario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Formulario</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Index">Formulario Bono</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Formulario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>